### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CarlLu** [hyperledger/fabric-gateway-java#107] opened 2022-04-13 20:50 UTC
public static Properties parseGrpcUrl(String url) {
  Pattern p = Pattern.compile("([^:]+)[:]//([^:]+)[:]([0-9]+)", Pattern.CASE_INSENSITIVE);
}

The regularity here will directly lead to errors，Please modify

**Comment by bestbeforetoday** [comment] 2022-04-27 10:35
Please could you provide more information on the specific failure scenario you see?

**Comment by bestbeforetoday** [comment] 2022-05-18 12:46
@CarlLu can you provide any more information on what the problem is and what needs to change? Otherwise I'll close this as there isn't enough information to progress it.

**Closed** 2022-05-20 17:06 UTC
Labels: question
